import { useState, useMemo, useEffect, useRef } from 'react'
import { useQuery, useMutation, useQueryClient } from '@tanstack/react-query'
import {
  listConfigs, getConfig, createConfig, updateConfig, deleteConfig,
  cloneConfig, importConfig, configExportUrl,
  type FullConfig, type ConfigRecord,
} from '../api'

// ── Default config ────────────────────────────────────────────────────────────

const DEFAULT_CONFIG: FullConfig = {
  encoder: {
    dim: 128, num_heads: 8, num_levels: 4, max_cams: 6, min_cams_train: 1,
    tpv_h: 200, tpv_w: 200, tpv_z: 16, num_encoder_layers: 5,
    scene_contraction: true, scene_contraction_factor: [0.5, 0.1, 0.1],
    offset: [-4.0, 0.0, 0.0], scale: [0.25, 0.25, 0.25],
    num_points_in_pillar: [4, 32, 32], num_points: [8, 64, 64],
    hybrid_attn_anchors: 16, hybrid_attn_points: 32,
  },
  decoder: {
    hidden_dim: 128, hidden_layers: 5, density_activation: 'trunc_exp',
    nb_bins: 64, nb_bins_sample: 64, hn: 0, hf: 60,
    train_stratified: true, white_background: false, whiteout: false,
    testing_batch_size: 8192,
  },
  optimizer: {
    lr: 5e-5, num_epochs: 100, num_warmup_steps: 1000,
    lpips_loss_weight: 0.2, tv_loss_weight: 0.0,
    dist_loss_weight: 1e-3, depth_loss_weight: 1.0, clip_grad_norm: 1.5,
  },
  dataset: {
    data_path: '/app/data/',
    train: {
      pickled: true, batch_size: 1, shuffle: true, num_workers: 12,
      towns: ['Town01', 'Town03', 'Town04', 'Town05', 'Town06', 'Town07', 'Town10HD'],
      weather: ['ClearNoon'], vehicle: ['vehicle.tesla.invisible'],
      factor: 0.08, num_imgs: 3, depth: true, min_cams_train: 1, max_cams_train: 6,
    },
    val: {
      pickled: false, phase: 'test', batch_size: 1, num_workers: 12,
      towns: ['Town02'], weather: ['ClearNoon'],
      vehicle: ['vehicle.tesla.invisible'],
      spawn_point: [3, 7, 12, 48, 98, 66], factor: 0.25, depth: true,
    },
  },
  pif: { enabled: false, factor: 0.125, transforms_path: '' },
}

// ── Live preview generator ────────────────────────────────────────────────────

function generatePreview(cfg: FullConfig): string {
  const e = cfg.encoder
  const d = cfg.decoder
  const o = cfg.optimizer
  const ds = cfg.dataset
  const p = cfg.pif
  // Layer split formula — keep in sync with export_to_py in config_io.py
  const nCross = Math.max(e.num_encoder_layers - 2, 1)
  const nSelf = e.num_encoder_layers - nCross
  return `# Generated by 6Img-to-3D Config Builder

_dim_ = ${e.dim}
num_heads = ${e.num_heads}
_num_levels_ = ${e.num_levels}
_max_cams_ = ${e.max_cams}
_min_cams_train_ = ${e.min_cams_train}

N_h_ = ${e.tpv_h}
N_w_ = ${e.tpv_w}
N_z_ = ${e.tpv_z}

offset = [${e.offset.join(', ')}]  # [z, h, w]
scale = [${e.scale.join(', ')}]    # [z, h, w]

scene_contraction = ${e.scene_contraction ? 'True' : 'False'}
scene_contraction_factor = [${e.scene_contraction_factor.join(', ')}]

pif = ${p.enabled ? 'True' : 'False'}
pif_factor = ${p.factor}
pif_transforms = "${p.transforms_path}"

tpv_encoder_layers = ${e.num_encoder_layers}
# ${nCross} cross-attn layers + ${nSelf} self-attn layers

decoder = dict(
    hidden_dim=${d.hidden_dim},
    hidden_layers=${d.hidden_layers},
    density_activation="${d.density_activation}",
    nb_bins=${d.nb_bins},
    nb_bins_sample=${d.nb_bins_sample},
    hn=${d.hn},
    hf=${d.hf},
    train_stratified=${d.train_stratified ? 'True' : 'False'},
    white_background=${d.white_background ? 'True' : 'False'},
    whiteout=${d.whiteout ? 'True' : 'False'},
    testing_batch_size=${d.testing_batch_size},
)

optimizer = dict(
    lr=${o.lr},
    num_training_steps=${o.num_warmup_steps},
    num_epochs=${o.num_epochs},
    lpips_loss_weight=${o.lpips_loss_weight},
    tv_loss_weight=${o.tv_loss_weight},
    dist_loss_weight=${o.dist_loss_weight},
    depth_loss_weight=${o.depth_loss_weight},
    clip_grad_norm=${o.clip_grad_norm},
)

dataset_params = dict(
    data_path="${ds.data_path}",
    train_data_loader=dict(
        towns=${JSON.stringify(ds.train.towns)},
        weather=${JSON.stringify(ds.train.weather)},
        factor=${ds.train.factor},
        num_imgs=${ds.train.num_imgs},
    ),
    val_data_loader=dict(
        towns=${JSON.stringify(ds.val.towns)},
        spawn_point=${JSON.stringify(ds.val.spawn_point)},
        factor=${ds.val.factor},
    ),
)
`
}

// ── UI primitives ─────────────────────────────────────────────────────────────

function Section({
  title, accent, children, defaultOpen = true,
}: {
  title: string; accent: string; children: React.ReactNode; defaultOpen?: boolean
}) {
  const [open, setOpen] = useState(defaultOpen)
  return (
    <div className={`border-l-2 ${accent} mb-3`}>
      <button
        onClick={() => setOpen(o => !o)}
        className="w-full flex items-center gap-2 px-3 py-2 text-left hover:bg-white/5 transition-colors"
      >
        <span className="text-xs font-semibold uppercase tracking-widest text-gray-300"
          style={{ fontFamily: 'DM Sans, sans-serif' }}>
          {title}
        </span>
        <span className="ml-auto text-gray-600 text-xs">{open ? '▲' : '▼'}</span>
      </button>
      {open && (
        <div className="px-3 pb-3 grid grid-cols-2 gap-x-4 gap-y-2">
          {children}
        </div>
      )}
    </div>
  )
}

function Field({ label, children, wide }: { label: string; children: React.ReactNode; wide?: boolean }) {
  return (
    <div className={wide ? 'col-span-2' : ''}>
      <label className="block text-xs text-gray-500 mb-0.5">{label}</label>
      {children}
    </div>
  )
}

const inputCls = 'w-full bg-gray-900 border border-gray-700 rounded px-2 py-1 text-xs text-gray-200 focus:border-gray-500 outline-none'
const monoStyle = { fontFamily: 'JetBrains Mono, monospace' }

function NumInput({ value, onChange, step, min }: {
  value: number; onChange: (v: number) => void; step?: number; min?: number
}) {
  return (
    <input type="number" value={value} step={step ?? 'any'} min={min}
      onChange={e => onChange(Number(e.target.value))}
      className={inputCls} style={monoStyle} />
  )
}

function TextInput({ value, onChange, placeholder }: {
  value: string; onChange: (v: string) => void; placeholder?: string
}) {
  return (
    <input type="text" value={value} placeholder={placeholder}
      onChange={e => onChange(e.target.value)}
      className={inputCls} style={monoStyle} />
  )
}

function Toggle({ value, onChange }: { value: boolean; onChange: (v: boolean) => void }) {
  return (
    <button onClick={() => onChange(!value)}
      className={`relative w-9 h-5 rounded-full transition-colors ${value ? 'bg-blue-600' : 'bg-gray-700'}`}>
      <span className={`absolute top-0.5 left-0.5 w-4 h-4 bg-white rounded-full transition-transform ${value ? 'translate-x-4' : ''}`} />
    </button>
  )
}

function TagInput({ values, onChange, numeric = false }: {
  values: (string | number)[];
  onChange: (v: (string | number)[]) => void;
  numeric?: boolean
}) {
  const [draft, setDraft] = useState('')

  function add() {
    const t = draft.trim()
    if (!t) return
    const val: string | number = numeric ? Number(t) : t
    onChange([...values, val])
    setDraft('')
  }

  return (
    <div className="flex flex-wrap gap-1 bg-gray-900 border border-gray-700 rounded p-1.5 min-h-[30px]">
      {values.map((v) => (
        <span key={String(v)} className="flex items-center gap-1 bg-gray-800 rounded px-1.5 py-0.5 text-xs text-gray-300"
          style={monoStyle}>
          {String(v)}
          <button onClick={() => onChange(values.filter((x) => x !== v))}
            className="text-gray-600 hover:text-red-400 leading-none">×</button>
        </span>
      ))}
      <input value={draft} onChange={e => setDraft(e.target.value)}
        onKeyDown={e => { if (e.key === 'Enter' || e.key === ',') { e.preventDefault(); add() } }}
        placeholder="add…"
        className="bg-transparent outline-none text-xs text-gray-300 min-w-[40px] flex-1"
        style={monoStyle} />
    </div>
  )
}

// ── Config form ───────────────────────────────────────────────────────────────

function ConfigForm({ cfg, onChange }: { cfg: FullConfig; onChange: (c: FullConfig) => void }) {
  const set = {
    enc: (k: string, v: unknown) => onChange({ ...cfg, encoder: { ...cfg.encoder, [k]: v } }),
    dec: (k: string, v: unknown) => onChange({ ...cfg, decoder: { ...cfg.decoder, [k]: v } }),
    opt: (k: string, v: unknown) => onChange({ ...cfg, optimizer: { ...cfg.optimizer, [k]: v } }),
    ds: (k: string, v: unknown) => onChange({ ...cfg, dataset: { ...cfg.dataset, [k]: v } }),
    tr: (k: string, v: unknown) => onChange({ ...cfg, dataset: { ...cfg.dataset, train: { ...cfg.dataset.train, [k]: v } } }),
    val: (k: string, v: unknown) => onChange({ ...cfg, dataset: { ...cfg.dataset, val: { ...cfg.dataset.val, [k]: v } } }),
    pif: (k: string, v: unknown) => onChange({ ...cfg, pif: { ...cfg.pif, [k]: v } }),
  }

  return (
    <div className="overflow-y-auto flex-1 pr-0.5 space-y-0">

      <Section title="Dataset" accent="border-cyan-500">
        <Field label="data_path" wide>
          <TextInput value={cfg.dataset.data_path} onChange={v => set.ds('data_path', v)} placeholder="/app/data/" />
        </Field>
        <Field label="train towns" wide>
          <TagInput values={cfg.dataset.train.towns} onChange={v => set.tr('towns', v)} />
        </Field>
        <Field label="train factor">
          <NumInput value={cfg.dataset.train.factor} onChange={v => set.tr('factor', v)} step={0.01} />
        </Field>
        <Field label="num_imgs">
          <NumInput value={cfg.dataset.train.num_imgs} onChange={v => set.tr('num_imgs', v)} step={1} min={1} />
        </Field>
        <Field label="val towns" wide>
          <TagInput values={cfg.dataset.val.towns} onChange={v => set.val('towns', v)} />
        </Field>
        <Field label="val spawn_points" wide>
          <TagInput values={cfg.dataset.val.spawn_point} onChange={v => set.val('spawn_point', v)} numeric />
        </Field>
        <Field label="val factor">
          <NumInput value={cfg.dataset.val.factor} onChange={v => set.val('factor', v)} step={0.01} />
        </Field>
        <Field label="val phase">
          <TextInput value={cfg.dataset.val.phase} onChange={v => set.val('phase', v)} />
        </Field>
      </Section>

      <Section title="Encoder" accent="border-violet-500">
        <Field label="dim">
          <NumInput value={cfg.encoder.dim} onChange={v => set.enc('dim', v)} step={1} min={1} />
        </Field>
        <Field label="num_heads">
          <NumInput value={cfg.encoder.num_heads} onChange={v => set.enc('num_heads', v)} step={1} min={1} />
        </Field>
        <Field label="tpv_h">
          <NumInput value={cfg.encoder.tpv_h} onChange={v => set.enc('tpv_h', v)} step={1} min={1} />
        </Field>
        <Field label="tpv_w">
          <NumInput value={cfg.encoder.tpv_w} onChange={v => set.enc('tpv_w', v)} step={1} min={1} />
        </Field>
        <Field label="tpv_z">
          <NumInput value={cfg.encoder.tpv_z} onChange={v => set.enc('tpv_z', v)} step={1} min={1} />
        </Field>
        <Field label="encoder layers">
          <NumInput value={cfg.encoder.num_encoder_layers} onChange={v => set.enc('num_encoder_layers', v)} step={1} min={3} />
        </Field>
        <Field label="scene_contraction">
          <Toggle value={cfg.encoder.scene_contraction} onChange={v => set.enc('scene_contraction', v)} />
        </Field>
        <Field label="contraction_factor" wide>
          <TagInput values={cfg.encoder.scene_contraction_factor} onChange={v => set.enc('scene_contraction_factor', v)} numeric />
        </Field>
        <Field label="offset [z,h,w]" wide>
          <TagInput values={cfg.encoder.offset} onChange={v => set.enc('offset', v)} numeric />
        </Field>
        <Field label="scale [z,h,w]" wide>
          <TagInput values={cfg.encoder.scale} onChange={v => set.enc('scale', v)} numeric />
        </Field>
      </Section>

      <Section title="Decoder" accent="border-emerald-500" defaultOpen={false}>
        <Field label="hidden_dim">
          <NumInput value={cfg.decoder.hidden_dim} onChange={v => set.dec('hidden_dim', v)} step={1} min={1} />
        </Field>
        <Field label="hidden_layers">
          <NumInput value={cfg.decoder.hidden_layers} onChange={v => set.dec('hidden_layers', v)} step={1} min={1} />
        </Field>
        <Field label="nb_bins">
          <NumInput value={cfg.decoder.nb_bins} onChange={v => set.dec('nb_bins', v)} step={1} min={1} />
        </Field>
        <Field label="nb_bins_sample">
          <NumInput value={cfg.decoder.nb_bins_sample} onChange={v => set.dec('nb_bins_sample', v)} step={1} min={1} />
        </Field>
        <Field label="near (hn)">
          <NumInput value={cfg.decoder.hn} onChange={v => set.dec('hn', v)} step={0.1} />
        </Field>
        <Field label="far (hf)">
          <NumInput value={cfg.decoder.hf} onChange={v => set.dec('hf', v)} step={1} />
        </Field>
        <Field label="density_activation" wide>
          <TextInput value={cfg.decoder.density_activation} onChange={v => set.dec('density_activation', v)} />
        </Field>
        <Field label="white_background">
          <Toggle value={cfg.decoder.white_background} onChange={v => set.dec('white_background', v)} />
        </Field>
        <Field label="whiteout">
          <Toggle value={cfg.decoder.whiteout} onChange={v => set.dec('whiteout', v)} />
        </Field>
        <Field label="testing_batch_size">
          <NumInput value={cfg.decoder.testing_batch_size} onChange={v => set.dec('testing_batch_size', v)} step={512} min={64} />
        </Field>
      </Section>

      <Section title="Optimizer" accent="border-amber-500" defaultOpen={false}>
        <Field label="lr">
          <NumInput value={cfg.optimizer.lr} onChange={v => set.opt('lr', v)} step={1e-6} />
        </Field>
        <Field label="num_epochs">
          <NumInput value={cfg.optimizer.num_epochs} onChange={v => set.opt('num_epochs', v)} step={1} min={1} />
        </Field>
        <Field label="warmup_steps">
          <NumInput value={cfg.optimizer.num_warmup_steps} onChange={v => set.opt('num_warmup_steps', v)} step={100} min={0} />
        </Field>
        <Field label="clip_grad_norm">
          <NumInput value={cfg.optimizer.clip_grad_norm} onChange={v => set.opt('clip_grad_norm', v)} step={0.1} />
        </Field>
        <Field label="lpips_weight">
          <NumInput value={cfg.optimizer.lpips_loss_weight} onChange={v => set.opt('lpips_loss_weight', v)} step={0.01} />
        </Field>
        <Field label="tv_weight">
          <NumInput value={cfg.optimizer.tv_loss_weight} onChange={v => set.opt('tv_loss_weight', v)} step={0.001} />
        </Field>
        <Field label="dist_weight">
          <NumInput value={cfg.optimizer.dist_loss_weight} onChange={v => set.opt('dist_loss_weight', v)} step={0.0001} />
        </Field>
        <Field label="depth_weight">
          <NumInput value={cfg.optimizer.depth_loss_weight} onChange={v => set.opt('depth_loss_weight', v)} step={0.1} />
        </Field>
      </Section>

      <Section title="PIF" accent="border-rose-500" defaultOpen={false}>
        <Field label="enabled">
          <Toggle value={cfg.pif.enabled} onChange={v => set.pif('enabled', v)} />
        </Field>
        <Field label="factor">
          <NumInput value={cfg.pif.factor} onChange={v => set.pif('factor', v)} step={0.001} />
        </Field>
        <Field label="transforms_path" wide>
          <TextInput value={cfg.pif.transforms_path} onChange={v => set.pif('transforms_path', v)}
            placeholder="/app/data/Town02/.../nuscenes/" />
        </Field>
      </Section>
    </div>
  )
}

// ── Main page ─────────────────────────────────────────────────────────────────

export default function ConfigBuilder() {
  const qc = useQueryClient()
  const [selectedId, setSelectedId] = useState<string | null>(null)
  const [cfg, setCfg] = useState<FullConfig>(DEFAULT_CONFIG)
  const [name, setName] = useState('untitled')
  const [importName, setImportName] = useState('')
  const [saving, setSaving] = useState(false)
  const [saveError, setSaveError] = useState<string | null>(null)
  const loadedIdRef = useRef<string | null>(null)

  const { data: configs = [] } = useQuery({ queryKey: ['configs'], queryFn: listConfigs })

  const { data: selected } = useQuery({
    queryKey: ['config', selectedId],
    queryFn: () => getConfig(selectedId!),
    enabled: !!selectedId,
  })

  useEffect(() => {
    if (selected && selected.id !== loadedIdRef.current && selected.data) {
      setCfg(selected.data)
      setName(selected.name)
      loadedIdRef.current = selected.id
    }
  }, [selected])

  const deleteMutation = useMutation({
    mutationFn: deleteConfig,
    onSuccess: () => {
      qc.invalidateQueries({ queryKey: ['configs'] })
      setSelectedId(null)
      setCfg(DEFAULT_CONFIG)
      setName('untitled')
      loadedIdRef.current = null
    },
  })

  const cloneMutation = useMutation({
    mutationFn: ({ id, n }: { id: string; n: string }) => cloneConfig(id, n),
    onSuccess: () => qc.invalidateQueries({ queryKey: ['configs'] }),
  })

  const preview = useMemo(() => generatePreview(cfg), [cfg])

  async function handleSave() {
    setSaving(true); setSaveError(null)
    try {
      if (selectedId) {
        await updateConfig(selectedId, name, cfg)
        qc.invalidateQueries({ queryKey: ['config', selectedId] })
      } else {
        const r = await createConfig(name, cfg)
        setSelectedId(r.id)
        loadedIdRef.current = r.id
      }
      qc.invalidateQueries({ queryKey: ['configs'] })
    } catch (e: unknown) {
      setSaveError(e instanceof Error ? e.message : 'Save failed')
    } finally {
      setSaving(false)
    }
  }

  async function handleImport(e: React.ChangeEvent<HTMLInputElement>) {
    const file = e.target.files?.[0]
    if (!file) return
    const n = importName.trim() || file.name.replace('.py', '')
    try {
      const r = await importConfig(n, file)
      qc.invalidateQueries({ queryKey: ['configs'] })
      setSelectedId(r.id)
      if (r.data) { setCfg(r.data); setName(r.name); loadedIdRef.current = r.id }
    } catch {
      setSaveError('Import failed — check that the file is a valid config.py')
    }
    e.target.value = ''
  }

  return (
    <div className="flex gap-0 h-[calc(100vh-5rem)]" style={{ fontFamily: 'DM Sans, sans-serif' }}>

      {/* ── Sidebar: config list ── */}
      <div className="w-52 shrink-0 border-r border-gray-800 flex flex-col">
        <div className="p-3 border-b border-gray-800 space-y-2">
          <div className="flex items-center justify-between">
            <span className="text-xs font-semibold uppercase tracking-widest text-gray-400">Configs</span>
            <button
              onClick={() => { setSelectedId(null); setCfg(DEFAULT_CONFIG); setName('untitled'); loadedIdRef.current = null }}
              className="text-xs bg-gray-800 hover:bg-gray-700 text-gray-300 rounded px-2 py-0.5">
              + New
            </button>
          </div>
          <div className="flex gap-1">
            <input value={importName} onChange={e => setImportName(e.target.value)}
              placeholder="import name"
              className="flex-1 min-w-0 bg-gray-900 border border-gray-700 rounded px-2 py-0.5 text-xs text-gray-300 outline-none" />
            <label className="cursor-pointer text-xs bg-gray-800 hover:bg-gray-700 text-gray-300 rounded px-2 py-0.5 whitespace-nowrap">
              Import
              <input type="file" accept=".py" onChange={handleImport} className="hidden" />
            </label>
          </div>
        </div>
        <div className="flex-1 overflow-y-auto p-2">
          {(configs as ConfigRecord[]).length === 0 && (
            <p className="text-xs text-gray-600 px-1 pt-1">No configs yet.</p>
          )}
          {(configs as ConfigRecord[]).map(r => (
            <button key={r.id} onClick={() => setSelectedId(r.id)}
              className={`w-full text-left rounded px-2 py-1.5 mb-0.5 text-xs transition-colors group ${selectedId === r.id ? 'bg-gray-800 text-gray-100' : 'text-gray-400 hover:bg-gray-900 hover:text-gray-200'}`}>
              <div className="font-medium truncate">{r.name}</div>
              <div className="flex gap-2 mt-0.5 opacity-0 group-hover:opacity-100 transition-opacity">
                <button onClick={e => { e.stopPropagation(); cloneMutation.mutate({ id: r.id, n: r.name + '-copy' }) }}
                  className="text-gray-600 hover:text-gray-300">clone</button>
                <button onClick={e => { e.stopPropagation(); if (confirm(`Delete "${r.name}"?`)) deleteMutation.mutate(r.id) }}
                  className="text-gray-600 hover:text-red-400">del</button>
              </div>
            </button>
          ))}
        </div>
      </div>

      {/* ── Center: form ── */}
      <div className="w-96 shrink-0 border-r border-gray-800 flex flex-col">
        <div className="p-3 border-b border-gray-800 flex items-center gap-2">
          <input value={name} onChange={e => setName(e.target.value)}
            className="flex-1 bg-gray-900 border border-gray-700 rounded px-2 py-1 text-sm text-gray-100 outline-none focus:border-gray-500" />
          <button onClick={handleSave} disabled={saving}
            className="text-xs bg-blue-700 hover:bg-blue-600 text-white rounded px-3 py-1 disabled:opacity-50">
            {saving ? 'Saving…' : 'Save'}
          </button>
          {selectedId && (
            <a href={configExportUrl(selectedId)} download
              className="text-xs bg-gray-800 hover:bg-gray-700 text-gray-300 rounded px-2 py-1">
              Export
            </a>
          )}
        </div>
        {saveError && <p className="text-red-400 text-xs px-3 pt-1">{saveError}</p>}
        <ConfigForm cfg={cfg} onChange={setCfg} />
      </div>

      {/* ── Right: live preview ── */}
      <div className="flex-1 flex flex-col bg-gray-950 min-w-0">
        <div className="px-4 py-2 border-b border-gray-800 flex items-center">
          <span className="text-xs text-gray-500 uppercase tracking-widest font-semibold">config.py preview</span>
          <span className="ml-auto text-xs text-gray-700">live</span>
        </div>
        <pre className="flex-1 overflow-auto p-4 text-xs leading-relaxed text-gray-300"
          style={{ fontFamily: 'JetBrains Mono, monospace' }}>
          {preview}
        </pre>
      </div>
    </div>
  )
}
