# webui/backend/services/config_io.py
import textwrap

from mmengine.config import Config as MMConfig

from webui.backend.schemas.config_schema import (
    DatasetConfig,
    DecoderConfig,
    EncoderConfig,
    FullConfig,
    OptimizerConfig,
    PIFConfig,
    TrainLoaderConfig,
    ValLoaderConfig,
)


def load_from_py(path: str) -> FullConfig:
    raw = MMConfig.fromfile(path)

    train_dl = raw.get("dataset_params", {}).get("train_data_loader", {})
    val_dl = raw.get("dataset_params", {}).get("val_data_loader", {})
    dec_raw = raw.get("decoder", {})
    opt_raw = raw.get("optimizer", {})
    ds_raw = raw.get("dataset_params", {})

    encoder = EncoderConfig(
        dim=raw.get("_dim_", 128),
        num_heads=raw.get("num_heads", 8),
        num_levels=raw.get("_num_levels_", 4),
        max_cams=raw.get("_max_cams_", 6),
        min_cams_train=raw.get("_min_cams_train_", 1),
        tpv_h=raw.get("N_h_", 200),
        tpv_w=raw.get("N_w_", 200),
        tpv_z=raw.get("N_z_", 16),
        num_encoder_layers=raw.get("tpv_encoder_layers", 5),
        scene_contraction=raw.get("scene_contraction", True),
        scene_contraction_factor=list(raw.get("scene_contraction_factor", [0.5, 0.1, 0.1])),
        offset=list(raw.get("offset", [-4.0, 0.0, 0.0])),
        scale=list(raw.get("scale", [0.25, 0.25, 0.25])),
        num_points_in_pillar=list(raw.get("num_points_in_pillar", [4, 32, 32])),
        num_points=list(raw.get("num_points", [8, 64, 64])),
        hybrid_attn_anchors=raw.get("hybrid_attn_anchors", 16),
        hybrid_attn_points=raw.get("hybrid_attn_points", 32),
    )

    decoder = DecoderConfig(
        hidden_dim=dec_raw.get("hidden_dim", 128),
        hidden_layers=dec_raw.get("hidden_layers", 5),
        density_activation=dec_raw.get("density_activation", "trunc_exp"),
        nb_bins=dec_raw.get("nb_bins", 64),
        nb_bins_sample=dec_raw.get("nb_bins_sample", 64),
        hn=dec_raw.get("hn", 0.0),
        hf=dec_raw.get("hf", 60.0),
        train_stratified=dec_raw.get("train_stratified", True),
        white_background=dec_raw.get("white_background", False),
        whiteout=dec_raw.get("whiteout", False),
        testing_batch_size=dec_raw.get("testing_batch_size", 8192),
    )

    optimizer = OptimizerConfig(
        lr=opt_raw.get("lr", 5e-5),
        num_epochs=opt_raw.get("num_epochs", 100),
        num_warmup_steps=opt_raw.get("num_training_steps", 1000),
        lpips_loss_weight=opt_raw.get("lpips_loss_weight", 0.2),
        tv_loss_weight=opt_raw.get("tv_loss_weight", 0.0),
        dist_loss_weight=opt_raw.get("dist_loss_weight", 1e-3),
        depth_loss_weight=opt_raw.get("depth_loss_weight", 1.0),
        clip_grad_norm=opt_raw.get("clip_grad_norm", 1.5),
    )

    dataset = DatasetConfig(
        data_path=ds_raw.get("data_path", "/app/data/"),
        train=TrainLoaderConfig(
            pickled=train_dl.get("pickled", True),
            batch_size=train_dl.get("batch_size", 1),
            shuffle=train_dl.get("shuffle", True),
            num_workers=train_dl.get("num_workers", 12),
            towns=list(train_dl.get("town", ["Town01"])),
            weather=list(train_dl.get("weather", ["ClearNoon"])),
            vehicle=list(train_dl.get("vehicle", ["vehicle.tesla.invisible"])),
            factor=train_dl.get("factor", 0.08),
            num_imgs=train_dl.get("num_imgs", 3),
            depth=train_dl.get("depth", True),
            min_cams_train=train_dl.get("min_cams_train", 1),
            max_cams_train=train_dl.get("max_cams_train", 6),
        ),
        val=ValLoaderConfig(
            pickled=val_dl.get("pickled", False),
            phase=val_dl.get("phase", "test"),
            batch_size=val_dl.get("batch_size", 1),
            num_workers=val_dl.get("num_workers", 12),
            towns=list(val_dl.get("town", ["Town02"])),
            weather=list(val_dl.get("weather", ["ClearNoon"])),
            vehicle=list(val_dl.get("vehicle", ["vehicle.tesla.invisible"])),
            spawn_point=list(val_dl.get("spawn_point", [3, 7, 12, 48, 98, 66])),
            factor=val_dl.get("factor", 0.25),
            depth=val_dl.get("depth", True),
        ),
    )

    pif = PIFConfig(
        enabled=bool(raw.get("pif", False)),
        factor=raw.get("pif_factor", 0.125),
        transforms_path=raw.get("pif_transforms", ""),
    )

    return FullConfig(encoder=encoder, decoder=decoder, optimizer=optimizer, dataset=dataset, pif=pif)


def export_to_py(cfg: FullConfig) -> str:
    e = cfg.encoder
    d = cfg.decoder
    o = cfg.optimizer
    ds = cfg.dataset
    p = cfg.pif
    train = ds.train
    val = ds.val

    n_cross = max(e.num_encoder_layers - 2, 1)
    n_self = e.num_encoder_layers - n_cross

    return textwrap.dedent(f"""\
        # Generated by 6Img-to-3D Config Builder
        # Do not edit manually — regenerate via the Config Builder webui.

        _dim_ = {e.dim}
        num_heads = {e.num_heads}
        _pos_dim_ = [48, 48, 32]
        _ffn_dim_ = _dim_ * 2
        _num_levels_ = {e.num_levels}
        _max_cams_ = {e.max_cams}
        _min_cams_train_ = {e.min_cams_train}

        N_h_ = {e.tpv_h}
        N_w_ = {e.tpv_w}
        N_z_ = {e.tpv_z}

        offset_z = {e.offset[0]}
        offset_h = {e.offset[1]}
        offset_w = {e.offset[2]}
        offset = [offset_z, offset_h, offset_w]
        scale_z = {e.scale[0]}
        scale_h = {e.scale[1]}
        scale_w = {e.scale[2]}
        scale = [scale_z, scale_h, scale_w]

        scene_contraction = {e.scene_contraction}
        scene_contraction_factor = {e.scene_contraction_factor}

        pif = {p.enabled}
        pif_factor = {p.factor}
        pif_transforms = "{p.transforms_path}"

        tpv_encoder_layers = {e.num_encoder_layers}
        num_points_in_pillar = {e.num_points_in_pillar}
        num_points = {e.num_points}
        hybrid_attn_anchors = {e.hybrid_attn_anchors}
        hybrid_attn_points = {e.hybrid_attn_points}
        hybrid_attn_init = 0

        self_cross_layer = dict(
            type="TPVFormerLayer",
            attn_cfgs=[
                dict(
                    type="TPVImageCrossAttention",
                    max_cams=_max_cams_,
                    deformable_attention=dict(
                        type="TPVMSDeformableAttention3D",
                        embed_dims=_dim_,
                        num_heads=num_heads,
                        num_points=num_points,
                        num_z_anchors=num_points_in_pillar,
                        num_levels=_num_levels_,
                        floor_sampling_offset=False,
                        tpv_h=N_h_,
                        tpv_w=N_w_,
                        tpv_z=N_z_,
                    ),
                    embed_dims=_dim_,
                    tpv_h=N_h_,
                    tpv_w=N_w_,
                    tpv_z=N_z_,
                ),
                dict(
                    type="TPVCrossViewHybridAttention",
                    tpv_h=N_h_,
                    tpv_w=N_w_,
                    tpv_z=N_z_,
                    num_anchors=hybrid_attn_anchors,
                    embed_dims=_dim_,
                    num_heads=num_heads,
                    num_points=hybrid_attn_points,
                    init_mode=hybrid_attn_init,
                ),
            ],
            feedforward_channels=_ffn_dim_,
            ffn_dropout=0.1,
            operation_order=("cross_attn", "norm", "self_attn", "norm", "ffn", "norm"),
        )

        self_layer = dict(
            type="TPVFormerLayer",
            attn_cfgs=[
                dict(
                    type="TPVCrossViewHybridAttention",
                    tpv_h=N_h_,
                    tpv_w=N_w_,
                    tpv_z=N_z_,
                    num_anchors=hybrid_attn_anchors,
                    embed_dims=_dim_,
                    num_heads=num_heads,
                    num_points=hybrid_attn_points,
                    init_mode=hybrid_attn_init,
                )
            ],
            feedforward_channels=_ffn_dim_,
            ffn_dropout=0.1,
            operation_order=("self_attn", "norm", "ffn", "norm"),
        )

        model = dict(
            type="TPVFormer",
            output_features=True,
            img_backbone=dict(
                type="ResNet",
                depth=101,
                num_stages=4,
                out_indices=(1, 2, 3),
                frozen_stages=1,
                norm_cfg=dict(type="BN2d", requires_grad=False),
                norm_eval=True,
                style="caffe",
                dcn=dict(type="DCNv2", deform_groups=1, fallback_on_stride=False),
                stage_with_dcn=(False, False, True, True),
            ),
            img_neck=dict(
                type="FPN",
                in_channels=[512, 1024, 2048],
                out_channels=_dim_,
                start_level=0,
                add_extra_convs="on_output",
                num_outs=4,
                relu_before_extra_convs=True,
            ),
            tpv_head=dict(
                type="TPVFormerHead",
                tpv_h=N_h_,
                tpv_w=N_w_,
                tpv_z=N_z_,
                num_feature_levels=_num_levels_,
                max_cams=_max_cams_,
                embed_dims=_dim_,
                encoder=dict(
                    type="TPVFormerEncoder",
                    tpv_h=N_h_,
                    tpv_w=N_w_,
                    tpv_z=N_z_,
                    offset=[offset_z, offset_h, offset_w],
                    scale=[scale_z, scale_h, scale_w],
                    intrin_factor=pif_factor,
                    scene_contraction=scene_contraction,
                    scene_contraction_factor=scene_contraction_factor,
                    num_layers=tpv_encoder_layers,
                    num_points_in_pillar=num_points_in_pillar,
                    num_points_in_pillar_cross_view=[16, 16, 16],
                    return_intermediate=False,
                    transformerlayers=[self_cross_layer] * {n_cross} + [self_layer] * {n_self},
                ),
                positional_encoding=dict(
                    type="CustomPositionalEncoding",
                    num_feats=_pos_dim_,
                    h=N_h_,
                    w=N_w_,
                    z=N_z_,
                ),
            ),
        )

        dataset_params = dict(
            data_path="{ds.data_path}",
            version="triplane",
            train_data_loader=dict(
                pickled={train.pickled},
                phase="train",
                batch_size={train.batch_size},
                shuffle={train.shuffle},
                num_workers={train.num_workers},
                town={train.towns},
                weather={train.weather},
                vehicle={train.vehicle},
                selection=["input_images", "sphere_dataset"],
                factor={train.factor},
                whole_image=True,
                num_imgs={train.num_imgs},
                depth={train.depth},
                min_cams_train={train.min_cams_train},
                max_cams_train={train.max_cams_train},
            ),
            val_data_loader=dict(
                pickled={val.pickled},
                phase="{val.phase}",
                batch_size={val.batch_size},
                shuffle=False,
                num_workers={val.num_workers},
                town={val.towns},
                weather={val.weather},
                vehicle={val.vehicle},
                spawn_point={val.spawn_point},
                step=["all"],
                selection=["input_images", "sphere_dataset"],
                factor={val.factor},
                depth={val.depth},
            ),
        )

        optimizer = dict(
            lr={o.lr},
            num_training_steps={o.num_warmup_steps},
            num_epochs={o.num_epochs},
            lpips_loss_weight={o.lpips_loss_weight},
            tv_loss_weight={o.tv_loss_weight},
            dist_loss_weight={o.dist_loss_weight},
            clip_grad_norm={o.clip_grad_norm},
            depth_loss_weight={o.depth_loss_weight},
        )

        decoder = dict(
            whiteout={d.whiteout},
            white_background={d.white_background},
            density_activation="{d.density_activation}",
            hidden_dim={d.hidden_dim},
            hidden_layers={d.hidden_layers},
            hn={d.hn},
            hf={d.hf},
            nb_bins={d.nb_bins},
            nb_bins_sample={d.nb_bins_sample},
            train_stratified={d.train_stratified},
            testing_batch_size={d.testing_batch_size},
        )
    """)
